[package]
name = "bincache-serve"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bincache-core   = { workspace = true }
bincache-ingest = { workspace = true }
bincache-store  = { workspace = true }

axum         = { workspace = true }
bytes        = { workspace = true }
futures-util = { workspace = true }
snafu        = { workspace = true }
swrite       = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }
tracing      = { workspace = true }

[dev-dependencies]
expect-test       = { workspace = true }
pretty_assertions = { workspace = true }
tokio             = { workspace = true }
zstd              = { workspace = true }

[lints]
workspace = true
