[package]
name = "bincache"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bincache-core   = { workspace = true }
bincache-index  = { workspace = true }
bincache-ingest = { workspace = true }
bincache-serve  = { workspace = true }
bincache-store  = { workspace = true }

clap               = { workspace = true }
compio             = { workspace = true, features = ["runtime"] }
lkv                = { workspace = true }
mimalloc           = { workspace = true }
snafu              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
